import type { Molecule } from '../mol-parser';
import { chargeModelResult } from '../chem/charge-model/bci-charges';
import { implicitHydrogenCounts } from '../chem/fill-hydrogens';

/**
 * Heavy-atom structural fingerprint used to guard fetched 3D structures.
 *
 * PubChem and CIR resolve the query by their own SMILES rules, and can
 * return a DIFFERENT compound than the one sketched — most notably JSME
 * emits aromatic lower-case SMILES ("c1ccc1" for a drawn cyclobutadiene),
 * and both services resolve that antiaromatic 4-ring form to the saturated
 * ring (cyclobutane, CID 9250). Without a check the app renders the wrong
 * molecule while reporting "PubChem 3D".
 *
 * The fingerprint ignores atom numbering (PubChem reorders atoms freely).
 * It compares each heavy atom with its hydrogen count, the heavy-heavy bond
 * multiset (element pair + order) and, since charges are part of a species'
 * identity, the NET formal charge — a charged sketch resolving to a neutral
 * (or differently charged) record is a different compound (the sketched
 * methyl anion must never be served methane).
 *
 * Hydrogens: the fetched record's are explicit; the sketch's are those drawn
 * plus the ones the local pipeline would fill (`implicitHydrogenCounts`).
 * The query is JSME's SMILES, whose hydrogens are JSME's own: it gives Ge,
 * As, Sb and Te none (`C[Ge]`, where the local pipeline makes GeH₃), and a
 * metal none. Without the count, a record of the hydrogen-poor radical
 * passed as "PubChem 3D" for a sketch the local pipeline builds saturated.
 * A mismatch falls through to that local pipeline.
 */
export function structuresMatch(fetched: Molecule, sketch: Molecule): boolean {
  return (
    arraysEqual(heavyAtomsWithHydrogens(fetched, false), heavyAtomsWithHydrogens(sketch, true)) &&
    arraysEqual(heavyBonds(fetched), heavyBonds(sketch)) &&
    netFormalCharge(fetched) === netFormalCharge(sketch)
  );
}

/** Net formal charge in electrons — the sum over every atom (0 when the
 *  parser found none). Hydrogens never carry one in practice, so this is
 *  the same over heavy atoms alone. */
function netFormalCharge(m: Molecule): number {
  let q = 0;
  for (const a of m.atoms) q += a.charge ?? 0;
  return q;
}

/**
 * True when a fetched structure's ion is one the MMFF94 BCI charge model
 * cannot represent at all (its Σ q_BCI cannot account for the drawn net
 * charge — the carbanion C⁻ most notably; MMFF94 has no carbon-anion type).
 * That is a GEOMETRY hazard, not just identity: the remote conformer was
 * generated by MMFF94 (PubChem's OMEGA pipeline) from NEUTRAL-type
 * parameters, so its shape for such an ion is an artifact — PubChem's
 * methanide comes back planar, where the real carbanion is pyramidal. The
 * caller rejects the fetch and lets the local pipeline build the honest
 * geometry instead. Ions the type space DOES represent with a primary q⁰
 * (ammonium N⁺, carboxylate O⁻, halides, ...) have residual exactly 0 and
 * pass — their PubChem conformers stay trusted.
 */
export function unrepresentableCharge(molecule: Molecule): boolean {
  try {
    const charged = chargeModelResult(molecule);
    // null = the library could not type/charge at all — no charge-gap signal,
    // so this gate says nothing (an untypeable ELEMENT is the parameter-gap
    // report's business, not the charge guard's).
    return charged !== null && Math.abs(charged.residual) > 1e-9;
  } catch {
    // The typing/charge machinery must never take the fetch down — no
    // signal means don't reject on this check.
    return false;
  }
}

/** Each heavy atom as element + hydrogen count ("CH3", "NiH0"): the H atoms
 *  bonded to it, plus — for a sketch — the implicit ones it would be given. */
function heavyAtomsWithHydrogens(m: Molecule, addImplicit: boolean): string[] {
  const hydrogens = addImplicit ? implicitHydrogenCounts(m) : m.atoms.map(() => 0);
  for (const bond of m.bonds) {
    const a1 = m.atoms[bond.atom1Index];
    const a2 = m.atoms[bond.atom2Index];
    if (!a1 || !a2) continue;
    if (a2.element === 'H' && a1.element !== 'H') hydrogens[bond.atom1Index]++;
    if (a1.element === 'H' && a2.element !== 'H') hydrogens[bond.atom2Index]++;
  }
  const out: string[] = [];
  m.atoms.forEach((a, i) => {
    if (a.element !== 'H') out.push(`${a.element}H${hydrogens[i]}`);
  });
  return out.sort();
}

function heavyBonds(m: Molecule): string[] {
  const out: string[] = [];
  for (const bond of m.bonds) {
    const a1 = m.atoms[bond.atom1Index];
    const a2 = m.atoms[bond.atom2Index];
    if (!a1 || !a2) continue;
    if (a1.element === 'H' || a2.element === 'H') continue;
    const [lo, hi] = a1.element < a2.element ? [a1.element, a2.element] : [a2.element, a1.element];
    out.push(`${bond.order}|${lo}-${hi}`);
  }
  return out.sort();
}

function arraysEqual(a: string[], b: string[]): boolean {
  if (a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) {
    if (a[i] !== b[i]) return false;
  }
  return true;
}
